from youtube_transcript_api import YouTubeTranscriptApi
import logging, sys
# Configure the logger
logging.basicConfig(filename='error.log', level=logging.ERROR)

my_video_id = sys.argv[1]
outls=[]

# this is Direct Trascript of Your YouTube

try:
    tx = YouTubeTranscriptApi.get_transcript(my_video_id)

    print(tx)

    for i in tx:
        #print(i)
        outxt = (i['text'])
        outls.append(outxt)

        with open("op.txt", "a") as opf:
            opf.write(outxt + "\n")
        
except Exception as e:
    # Log the exception along with additional information
    logging.error('An error occurred while get_transcript AND OR Writing to File: %s', str(e))



# this is Additional Loggings of Your YouTube trascript
    
# try:
#     transcript_list = YouTubeTranscriptApi.list_transcripts(my_video_id)
#     transcript = transcript_list.find_transcript(['en'])
#     print("video_id $$$ ",transcript.video_id)
#     print(transcript.language)
#     print(transcript.language_code)
#         # whether it has been manually created or generated by YouTube
#     print(transcript.is_generated)
#         # whether this transcript can be translated or not
#     print(transcript.is_translatable)
#         # a list of languages the transcript can be translated to
#     print(transcript.translation_languages)
# except Exception as e:
#     # Log the exception along with additional information
#     logging.error('An error occurred: %s', str(e))




# this is traslation of Trascript of Your YouTube to Lang you desire
try:
    transcript_list = YouTubeTranscriptApi.list_transcripts(my_video_id)

    my_language_code = sys.argv[2]
    my_language_code_exists = False
    count = 0
    for transcript in transcript_list:
        tx_langs = transcript.translation_languages

        for langs in tx_langs:
            if my_language_code == langs['language_code']:
                my_language_code_exists = True
                count = count+1
                print('Matching Translation is possible')
                break;
            
        if my_language_code_exists and count==1:
            translated = transcript.translate(my_language_code).fetch()
            print(translated)
            transcriptOfTranslated = []
            for x in translated:
                translatedtxt = (x['text'])
                transcriptOfTranslated.append(translatedtxt)
            print(' '.join(transcriptOfTranslated))

        else:
            print(transcript.fetch())

        if my_language_code_exists:
                print('Already my_language_code_exists is ',my_language_code_exists)
                break;

except Exception as e:
    # Log the exception along with additional information
    logging.error('An error occurred: %s', str(e))